---
name: Build

on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "renovate.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "renovate.json"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "22"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache local Maven repository
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        # Run the "verify" target so that the "integration-test" phase is run which contains the native tests
        # See: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#default-lifecycle
        run: ./mvnw -Dstyle.color=always --no-transfer-progress -P native clean verify
      - name: Test application
        run: |
          file ./target/kotlin-cli
          ./target/kotlin-cli file-io
          ./target/kotlin-cli network-io --url https://utkuozdemir.org
          ./target/kotlin-cli data-class
