---
name: Build

on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "renovate.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "renovate.json"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          # renovate: depName=graalvm/graalvm-ce-builds datasource=github-releases extractVersion=^vm-(?<version>\d+\.\d+\.\d+)$
          graalvm: 22.2.0
          java: java17
      - name: Cache local Maven repository
        uses: actions/cache@v3.0.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        # Run the "verify" target so that the "integration-test" phase is run which contains the native tests
        # See: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#default-lifecycle
        run: ./mvnw -Dstyle.color=always --no-transfer-progress -P native clean verify
      - name: Test application
        run: |
          file ./target/kotlin-cli
          ./target/kotlin-cli file-io
          ./target/kotlin-cli network-io --url https://utkuozdemir.org
          ./target/kotlin-cli data-class
